spring.application.name=EmpPayroll7

server.port=8080    
spring.datasource.url=jdbc:postgresql://localhost:5432/EmpPayroll7
spring.datasource.username=postgres
spring.datasource.password=5481
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
